apiVersion: v1
kind: Secret
metadata:
  name: demo-app-secret
type: Opaque
data:
  telegramToken: {{ .Values.telegram.token | b64enc | quote }}
  notionAppSecret: {{ .Values.notion.appSecret | b64enc | quote }}
  notionDatabaseId: {{ .Values.notion.databaseId | b64enc | quote }}
  tonApiKey: {{ .Values.ton.apiKey | b64enc | quote }}
  apiSecret: {{ .Values.api.env.secret | b64enc | quote }}