telegram:
    token: ENC[AES256_GCM,data:knyVm7ijJEr1/64Hl1j37UUpBktIDz7QLYdDyrlWiH5p5O/USECrJJwzkvaOCQ==,iv:xyqQBR7EG2uPjTi7LtOxUmYulD9D/rJuL+Pjc6V3dqs=,tag:4nS1fF7SyDt1bMBsdTHNUg==,type:str]
notion:
    appSecret: ENC[AES256_GCM,data:KqyfPrttnoQaLhJS+/luYnfVmZN2t3v3H4XJDykQHY/akfu539c6YnCNp+LlvadSw7U=,iv:xulSSGDwDhOGe8x6b5t3+9AO2ZjDkbar2Mw2kw6PQQQ=,tag:/946HX5YVlFfdyPAQy86FA==,type:str]
    databaseId: ENC[AES256_GCM,data:fS1bgrUBDSm90xKValu7jp0wqNvQtN80Xk/nHqJyQx4=,iv:VqRyRPidCBtDMic9/NzobLQaZcTwCLff5Zfd0Q2LIXY=,tag:sf3uza3UCxZi+tz9BCPkYA==,type:str]
ton:
    apiKey: ENC[AES256_GCM,data:wXIxj1mcJ+Q+F5PvykcePF8Hc972n8Ag9c2fZyP/WdS3DVMCrgqz7Jy3xYBMfNtlc68O7QVWZCC7u2KSBezuzB/V9IzsSJw=,iv:A+h3VvzjEgtiRniq6pYLeKHHG4uMDrg2oc/jpfpeito=,tag:LKe7EPrsg3Bpj0omSgZHjQ==,type:str]
api:
    env:
        secret: ENC[AES256_GCM,data:DL+7wZSMLECPiGT4PlyGcIvIISeWz3eDOMobtJtnHpI=,iv:q2C6qxPRBqSbc+OQyqMK8W2W5UGynkomZyoAeycKKAM=,tag:PSY+0rxXxV6rO+AdPypl6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-10T23:36:49Z"
    mac: ENC[AES256_GCM,data:7QqBYpPx8zdFrPX4KOozyBHZohwV0iaFW3sZzWWJ3yfucYvke3fA+n9np+M9p8wuQE0jdZ5n9j9DWLYeii4vwJkAdQJUTgIQsW/dwq2cSogUNguUiUsMVijrkxe5eA4cI5EdAptbtsdjX6Sh4RJhANEV0ldzuQpjoNVoUerKKF0=,iv:imv3kGr6gH8aLne0PswfFIvS57sW1Kr3ypEWGkU5MEc=,tag:biidtjMWosU4ntqHC0VYpQ==,type:str]
    pgp:
        - created_at: "2025-01-10T23:36:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAxyTKrbD150xARAAh6xSWYJ2a9r0nMQ1cViPrkh0qZesu89cdmlLpo42r3JW
            PXI23GneaL/yE0vT8Ue2jetnKmgcOTwl5k/USBf17o4xqS43Au2RvsxA9AP0V2/H
            I+1NiypvwTMuLIXIXMUaC65KzVWrbP9v0hAJSK8Rj2YE+dl97IrjOQ2hYNKJaWZt
            Nbs4zCT+HcsTZJu8pvIq/7r1NzKbkhpxXf30g7xIid7h247lboQqKGdhDYu2ywq/
            82VPFHzwil3mpPAbbDI8ADAyQd2Zff4uU6+Cq2pL65vavexMPW5BD4A7jYBB2HQ/
            PweXbB64bjp2Hz+QaozpiFVlFrjjBWq9LeR/FstolWsrntw4i3zhU5IgK3QTHyL4
            ZPzq6pewpgZLewdLG82Koqr/SqzFYGK80A6vK/oY8P3E2z2PRgY/vMEbaVaKMhI/
            GGA6Iwjezyy7lIPyrRe8iljzPXl9SNaXnwf87Ipg67n3KKmQfiGalN6MNAHMqgc9
            708wILpmEZKSX6NPy6T27z0y3E3otyHq/6hgMVu1kk2m9R828sRKrff2fdO5wG7B
            Af1xPbjbLVSTKYcZErBpdWVceAxvse+qHaQK9OuZ4+hZpiukrPB9oVwmUqz1JBPz
            0v39B9i50tjwQUyxflNrpvMxvCGYQBSPCoYHgbxeVHYnDOtbwvAs2RKe/YDJOzzU
            aAEJAhDIJiRakdDjCE/1segrCcEa+t905MbXrYTbJ14qWg5EywknGipHxUO0lC9W
            bQr0SM5vKXPHc9VuHLHHvDoR+Q9rjqvIvBU7mg7cRgc+h24l33EGwqyKiS05pGtG
            4XG0ZgYANTvw
            =Rc1g
            -----END PGP MESSAGE-----
          fp: 120391F513F154BD98820AB2183FF3C9E923BF80
    unencrypted_suffix: _unencrypted
    version: 3.9.1
